In [19]:
import numpy as np

np.set_printoptions(precision = 3, suppress = True)
x = np.array([
    [1.0 , 2.0 , 30.0],
    [2.0 , 4.0 , 32.0],
    [3.0 , 6.0 , 28.0],
    [4.0 , 8.0 , 34.0],
])

print("INPUT DATA:\n" , x)

INPUT DATA:
 [[ 1.  2. 30.]
 [ 2.  4. 32.]
 [ 3.  6. 28.]
 [ 4.  8. 34.]]


In [20]:
eps = 1e-5

mean = x.mean(axis = 0)
var = x.var(axis = 0)

print("MEAN PER FEATURE :", mean)
print("VARIANCE PER FEATURE :", var)

MEAN PER FEATURE : [ 2.5  5.  31. ]
VARIANCE PER FEATURE : [1.25 5.   5.  ]


In [21]:
x_hat = (x - mean) / np.sqrt(var + eps)

print("\nNORMALISED x (x_hat) :\n\n" ,x_hat)

print("\nNEW MEAN PER FEATURE (should be ~0):", x_hat.mean(axis = 0))

print("\nNEW VAR PER FEATURE (should be ~1):", x_hat.var(axis = 0))


NORMALISED x (x_hat) :

 [[-1.342 -1.342 -0.447]
 [-0.447 -0.447  0.447]
 [ 0.447  0.447 -1.342]
 [ 1.342  1.342  1.342]]

NEW MEAN PER FEATURE (should be ~0): [0. 0. 0.]

NEW VAR PER FEATURE (should be ~1): [1. 1. 1.]


In [22]:
gamma = np.ones(3)
beta = np.zeros(3)

out = gamma * x_hat + beta
print("OUTPUT AFTER gamma/beta :\n" , out)

OUTPUT AFTER gamma/beta :
 [[-1.342 -1.342 -0.447]
 [-0.447 -0.447  0.447]
 [ 0.447  0.447 -1.342]
 [ 1.342  1.342  1.342]]


In [23]:
mean_ln = x.mean(axis = 1, keepdims = True)
var_ln = x.var(axis = 1, keepdims = True)

x_hat_ln = (x - mean_ln) / np.sqrt(var_ln + eps)

print("LAYERNORM NORMALISED (x) :\n" , x_hat_ln)

print("\nROW MEANS (should be ~0) :", x_hat_ln.mean(axis = 1))

print("\nROW VARS (should be ~1) :", x_hat_ln.var(axis = 1))

LAYERNORM NORMALISED (x) :
 [[-0.744 -0.67   1.414]
 [-0.779 -0.633  1.412]
 [-0.837 -0.568  1.406]
 [-0.852 -0.551  1.404]]

ROW MEANS (should be ~0) : [ 0.  0. -0. -0.]

ROW VARS (should be ~1) : [1. 1. 1. 1.]
